services:
  trade_bot:
    build: .
    container_name:  trade_bot_crypto_impulse
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - NODE_ENV=production
